# HTTP 代理配置
#systemProp.http.proxyHost=127.0.0.1
#systemProp.http.proxyPort=10808
# HTTPS 代理配置
#systemProp.https.proxyHost=127.0.0.1
#systemProp.https.proxyPort=10808
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.71
mod_id=wizardry
mod_name=Wizardry
mod_license=MIT
mod_version=1.0.0
mod_description=Electroblob's Wizardry adds an rpg-style system of magic spells to Minecraft with the aim of being as playable as possible. No crazy constructs, no perk trees, no complex recipes - simply find spell books, cast spells, and master the arcane!
mod_group_id=top.begonia.wizardry
jei_version=30.2.0.18
mod_authors=QiuHaiTangHong
